FROM node:16-alpine as builder
WORKDIR /app
COPY . .
RUN yarn install --frozen-lockfile
RUN yarn build
RUN rm -rf ./node_modules && yarn install --frozen-lockfile --production --ignore-scripts

FROM node:16-alpine
EXPOSE 3000
WORKDIR /app
COPY --from=builder /app .
ENTRYPOINT ["node"]
CMD [".output/server/index.mjs"]
